name: x-cmd ready
description: Prepare x-cmd
inputs:
  entrypoint:
    description: running bash script
    require: false
  shellcode:
    description: running bash code
    require: false
  ref:
    description: checkout ref
    required: false
  docker_username:
    description: checkout repo name
    required: false
  docker_password:
    description: checkout repo name
    required: false
  init_buildx:
    description: buildx init
    required: false

runs:
  using: "composite"
  steps:
    - name: git checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.ref || github.ref_name }}
        fetch-depth: 0
    - name: x-cmd installation
      run: |
          eval "$(curl https://get.x-cmd.com/dev)" || true
          ___X_CMD_IN_CHINA_NET=
      shell: bash
    - name: Docker login
      run: docker login -u "${{ inputs.docker_username }}" -p "${{ inputs.docker_password }}"
      if: ${{ (inputs.docker_username != null) && (inputs.docker_password != null) }}
      shell: bash
    - name: Docker buildx init
      run: docker buildx create --use
      if: ${{ inputs.buildx != null }}
      shell: bash
    - name: Running Script
      run: |
          . $HOME/.x-cmd/.boot/boot || true
          cat "${{ inputs.entrypoint }}"
          . "${{ inputs.entrypoint }}"
      if: ${{ inputs.entrypoint != null }}
      shell: bash
    - name: Running Code
      run: |
          . $HOME/.x-cmd/.boot/boot || true
          ${{ inputs.shellcode }}
      if: ${{ inputs.shellcode != null }}
      shell: bash
