name: x-cmd ready
description: Prepare x-cmd
inputs:
  ref:
    description: checkout ref
    required: false
  docker_username:
    description: checkout repo name
    required: false
  docker_password:
    description: checkout repo name
    required: false
  entrypoint:
    description: running bash script
    require: false
  shellcode:
    description: running bash code
    require: false
runs:
  using: "composite"
  steps:
    - name: git checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ inputs.ref || github.ref_name }}
        fetch-depth: 0
    - name: x-cmd installation
      run: |
        eval "$(curl https://get.x-cmd.com/dev)" || true
        ___X_CMD_IN_CHINA_NET=
      shell: bash
    - name: Docker buildx init
      run: |
        if [ -n "$DOCKER_USERNAME" ] && [ -n "$DOCKER_PASSWORD" ]; then
          docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
          docker buildx create --use
        fi
      if: ${{ (inputs.docker_username != null) && (inputs.docker_password != null) }}
      env:
        DOCKER_USERNAME: ${{ inputs.docker_username }}
        DOCKER_PASSWORD: ${{ inputs.docker_password }}
      shell: bash
    - name: Running Script
      run: |
          . $HOME/.x-cmd/.boot/boot || true
          . "${{ inputs.entrypoint }}"
      if: ${{ inputs.entrypoint != null }}
      shell: bash
