name: X-Action
description: X-Action
runs:
  using: "composite"
  steps:
    - name: Init ssh agent
      uses: webfactory/ssh-agent@v0.5.4
      if: ${{ env.ssh_key != null }}
      with:
        ssh-private-key: ${{ env.ssh_key }}
    - name: init x-cmd, git, docker, ssh
      run: eval "$(curl -s https://raw.githubusercontent.com/x-cmd/action/main/lib/index.sh | tee ~/.init)"; init_main
      shell: bash
    - name: Running Script
      run: |
          . ~/.init run_script_before
          ${{ env.before }}
          . "$___X_CMD_INSIDE_GITHUB_ACTION"
          ${{ env.after }}
      if: ${{ (env.entrypoint != null) || (hashFiles( format( '.x-cmd/{0}', github.job ) ) != '' ) }}
      env:
        ___X_CMD_INSIDE_GITHUB_ACTION: ${{ env.entrypoint || format( '.x-cmd/{0}', github.job ) }}
      shell: bash
    - name: Running Code
      run: |
          . ~/.init run_shellcode_before
          ${{ env.shellcode }}
      if: ${{ env.shellcode != null }}
      shell: bash
