name: X-Action
description: X-Action
runs:
  using: "composite"
  steps:
    - name: init x-cmd, git, docker, ssh
      run: eval "$(curl -s https://raw.githubusercontent.com/x-cmd/action/main/lib/index.sh | tee ~/.init)"; init_main
      shell: bash
    - name: Running Script
      run: |
          . ~/.init run_script_before
          ${{ env.before }}
          . "$___X_CMD_INSIDE_GITHUB_ACTION"
          ${{ env.after }}
      env:
        ___X_CMD_INSIDE_GITHUB_ACTION: ${{ input.entrypoint || env.entrypoint || format( '.x-cmd/{0}', github.job ) }}
      if: ${{ hashFiles( env.___X_CMD_INSIDE_GITHUB_ACTION ) != '' }}
      shell: bash
    - name: Running Code
      run: |
          . ~/.init run_shellcode_before
          ${{ env.shellcode }}
      if: ${{ env.shellcode != null }}
      shell: bash
