name: X-Action
description: X-Action

inputs:
  prehook:
    description: shellcode before execution of entrypoint
    required: false
  script:
    description: script for execution with bash
    required: false
  code:
    description: bash code for execution
    required: false
  posthook:
    description: shellcode after execution of entrypoint
    required: false

  git_ref:
    description: checkout ref
    required: false
  git_url:
    description: checkout url
    required: false

  ssh_key:
    description: ssh key
    required: false
  git_user:
    description: Git Commit Username
    required: false
  git_email:
    description: Git Commit Email
    required: false

  docker_username:
    description: Username for Docker login
    required: false
  docker_password:
    description: Password for Docker login
    required: false
  docker_buildx_init:
    description: buildx init
    required: false

runs:
  using: "composite"
  steps:
    - name: init x-cmd, git, docker, ssh
      shell: bash
      env:
        ssh_key: ${{ inputs.ssh_key || env.ssh_key }}
        git_ref: ${{ inputs.git_ref || env.git_ref || github.ref_name }}
        git_url: ${{ inputs.git_url || env.git_url || github.event.repository.ssh_url }}
        git_user: ${{ inputs.git_user || env.git_user || github.event.head_commit.author.name }}
        git_email: ${{ inputs.git_email || env.git_email || github.event.head_commit.author.email }}
        docker_username: ${{ inputs.docker_username || env.docker_username }}
        docker_password: ${{ inputs.docker_password || env.docker_password }}
        docker_buildx_init: ${{ inputs.docker_buildx_init || env.docker_buildx_init }}
      run:
        curl -s https://raw.githubusercontent.com/x-cmd/action/main/lib/index.sh > ~/xghaction
        . ~/xghaction init

    - name: Running Script
      shell: bash
      env:
        ___X_CMD_GHACTION_PREHOOK: ${{ inputs.prehook || env.prehook  }}
        ___X_CMD_GHACTION_SCRIPT: ${{ inputs.script || env.script || format( '.x-cmd/{0}', github.job ) }}
        ___X_CMD_GHACTION_CODE: '${{ inputs.code }}'
        ___X_CMD_GHACTION_POSTHOOK: ${{ inputs.posthook || env.posthook }}
      run: bash ~/xghaction run
