name: x-cmd ready
description: Prepare x-cmd
inputs:
  ref:
    description: checkout repo name
    required: false
runs:
  using: "composite"
  steps:
    - name: x-cmd installation
      run: |
        eval "$(curl https://get.x-cmd.com/dev)" || true
        ___X_CMD_IN_CHINA_NET=
      shell: bash
