name: Try to do some thing
on:
  push:
  # workflow_dispatch:

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: Building
        uses: x-cmd/action@main
        env:
          entrypoint: exp/a.sh
