name: Use upload artifact
on:
  # push:
  workflow_dispatch:

jobs:
  publisher:
    runs-on: ubuntu-latest
    env:
      # github_token: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      # ___X_CMD_GHACTION_X: x1
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          # code: x log +yanfa && x ws pub || true
          code: x ws art || true
          artifact_name: artifact
          artifact_path: ~/work/action/action/ws/.artifact
