name: Try to do some thing
on:
  # push:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: x-cmd/action@main
      - with:
          shellcode: xws build linux
    
  macos:
    runs-on: macos-11
    steps:
      - uses: x-cmd/action@main
      - with:
          shellcode: xws build macos
