name: Use x-cmd docker image
on:
  # push:
  workflow_dispatch:

# NOTE: Error: Container operations are only supported on Linux runners
jobs:
  publisher:
    strategy:
        matrix:
          image: [xcmd/ubuntu-dev, xcmd/centos-dev]
    container:
        image: ${{ matrix.image }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      ___X_CMD_CODESORUCE_REPO: dev
      CONCURRENCY: 10

    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws build ${{ matrix.image }}
