name: Use x-cmd docker image
on:
  # push:
  workflow_dispatch:

jobs:
  publisher:
    strategy:
        matrix:
          os: [ ubuntu-latest]
          image: [xcmd/base-ubuntu-2-dev, xcmd/base-centos-2-dev]
    container:
        image: ${{ matrix.image }}
    runs-on: ${{ matrix.os }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      ___X_CMD_CODESORUCE_REPO: dev
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws build xcmd/ubuntu-dev
