name: Use x-cmd docker image
on:
  # push:
  workflow_dispatch:

# NOTE: Error: Container operations are only supported on Linux runners
jobs:
  Build:
    strategy:
        matrix:
          image: [xcmd/ubuntu-dev, xcmd/centos-dev]
    container:
        image: ${{ matrix.image }}
    runs-on: ubuntu-latest
    env:
      # github_token: ${{ secrets.GITHUB_TOKEN }}
      # ___X_CMD_GHACTION_X: x1
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10

    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws build ${{ matrix.image }}
