name: Cowsay
on:
  # push:
  workflow_dispatch:

jobs:
  cowsay:
    runs-on: ubuntu-latest
    steps:
      - uses: x-cmd/action@main
        env:
          shellcode: git clone git@github.com:x-cmd/theme.git; ls theme
          ssh_key: '${{ secrets.ssh_key }}'
    
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: x-cmd/action@main
