name: Cowsay
on:
  # push:
  workflow_dispatch:
    inputs:
      name:
        description: 'Test'
        default: 'x-cmd'

jobs:
  cowsay:
    strategy:
        matrix:
          image: [xcmd/ubuntu-dev, xcmd/centos-dev]
    container:
        image: ${{ matrix.image }}
    runs-on: ubuntu-latest
    env:
      # github_token: ${{ secrets.GITHUB_TOKEN }}
      ___X_CMD_GHACTION_X: x2
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      - uses: x-cmd/action@main
        with:
          code: |
            echo "Hello World"
            ls
            x cowsay "hello world"
            echo "${{ github.event.inputs.name }}"
