name: Cowsay
on:
  # push:
  workflow_dispatch:
    inputs:
      name:
        description: 'Test'
        default: 'x-cmd'

jobs:
  cowsay:
    runs-on: ubuntu-latest
    env:
      # github_token: ${{ secrets.GITHUB_TOKEN }}
      # ___X_CMD_GHACTION_X: x1
      CONCURRENCY: 10
    steps:
      - uses: x-cmd/action@main
        with:
          code: |
            echo "Hello World"
            ls
            x cowsay "hello world"
            echo "${{ github.event.inputs.name }}"
