name: Cowsay
on:
  # push:
  workflow_dispatch:

jobs:
  cowsay:
    runs-on: ubuntu-latest
    env:
      ssh_key: '${{ secrets.ssh_key }}'
      docker_username: '${{ secrets.docker_username }}'
      docker_password: '${{ secrets.docker_password }}'
    steps:
      - uses: x-cmd/action@main
        env:
          shellcode: git clone git@github.com:x-cmd/theme.git; ls theme
    
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: x-cmd/action@main
