name: Cowsay
on:
  push:
  # workflow_dispatch:

jobs:
  cowsay:
    runs-on: ubuntu-latest
    env:
      ssh_key: '${{ secrets.ssh_key }}'
    steps:
      - uses: x-cmd/action@main
        with:
          code: git clone git@github.com:x-cmd/theme.git; ls theme

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: x-cmd/action@main
