name: Cowsay
on:
  # push:
  workflow_dispatch:

jobs:
  cowsay:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: x-cmd/action@main
        with:
          code: |
            echo "Hello World!"
            ls
            x cowsay "hello world!"
