name: Try to do some thing
on:
  push:
  # workflow_dispatch:

jobs:
  cowsay:
    runs-on: ubuntu-latest
    steps:
      - uses: x-cmd/action@main
    
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: x-cmd/action@main
