name: Cowsay
on:
  # push:
  workflow_dispatch:
    inputs:
      name:
        description: 'Test'
        default: 'x-cmd'

jobs:
  cowsay:
    container:
      image: xcmd/ubuntu-dev
    runs-on: ubuntu-latest
    env:
      # github_token: ${{ secrets.GITHUB_TOKEN }}
      # ___X_CMD_GHACTION_X: x1
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY }}
      git_user: agent-zero
      git_email: 0@x-cmd.com
      CONCURRENCY: 10
    steps:
      # - uses: x-cmd/action@main
      - uses: x-cmd/action@v0
        with:
          code: |
            echo "Hello World"
            ls
            x cowsay "hello world"
            echo "${{ github.event.inputs.name }}"
