name: Try to do some thing
on:
  # push:
  workflow_dispatch:

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - name: install x-cmd && setup ssh publish
        uses: x-cmd/action@main
        
        with:
          shellcode: x install ls
          entrypoint: .x-cmd/cowsay
